config/routes.rb
AwesomeAnswers::Application.routes.draw do
  devise_for :users
  root 'projects#index'

  get "/password" => "home#password"

  get "/about_us" => "home#about"

  get "/help" => "help#index"

  
  resources :questions do
    resources :answers
    member do#create a special action of vote_up int he controller. on: :member makes it take an ID
      post :vote_up 
      post :vote_down
    end
    post :search, on: :collection#collection means NO ID...
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :category
  belongs_to :question
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations, dependent: :destroy
  has_many :questions, through: :categorizations
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  validates :title, presence: true, uniqueness: true
  validates :description, presence: {message: "must be present"}

  scope :recent_ten, -> { order("created_at").limit(10)} #like the def
  scope :recent, lambda {|x| order("created_at DESC").limit(x)} #takes an argument

  belongs_to :user
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  #default_scope order("title ASC") #this will run on ALL Queries

  #get the newest 10
  # def self.recent_ten
  #   order("created_at DESC").limit(10)
  # end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :find_question
                only: [:create, :destroy]

  def index   
  end

  def create
    #@question = Question.find params[:question_id]
    @answer = @question.answers.new(answer_attributes)
    @answer.user = current_user # you don't filter through the user, cause you want the answers for teh question
                                # not the answer that the user has done. The user hasn't asked this question.
    
    if @answer.save
      redirect_to @question, notice: "Answer created successfully"
    else
      render "/questions/show", error: "Error, question not added"
    end
  end

  def destroy
    @answer = @question.answer.find(params[:id])
    if @answer.destroy
      redirect_to @question, notice: "Answer Deleted"
    else
      redirect_to @question, error: "Answer not deleted"
    end
  end

  def new 
  end

  def update
  end

  private

  def answer_attributes
    params.require(:answer).permit([:body])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/help_controller.rb
class HelpController < ApplicationController

  def index
    
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

  def password
    
  end

  def about
    render text: "I AM SNORTING (ROUTING) RAILS"
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  before_action :find_question,
                  only: [:edit, :destroy, :update, :vote_up, :vote_down]
  #before_action :find_question, except: [:index, :new, :destroy, :update]

  #index is the standard for displaying all the questions
  def index
    @questions = Question.all    
  end

  def create
    #because the current_user has the question object connected to it, you can
    #use the current user to create a new questiona and also have a user ID connected to it
    #of the current user.
    #Same as @question = Question.new(question_attributes)
    #and @question.user = current_user
    @question = current_user.questions.new(question_attributes)

    if @question.save #check for validation errors etc, that it was entered into the datbase
      redirect_to questions_path, notice: "Your question was submitted and will be answered soon"
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def edit
  end

  def update
    if @question.update_attributes(question_attributes)
      redirect_to @question, notice: "Your question was updated!"
    else
      render :edit
    end
  end

  def vote_up
    @question.increment!(:vote_count) # ! auto saves to database
    session[:has_voted] = true
    redirect_to @question
  end

  def vote_down
  end

  def destroy
    if @question.destroy
      redirect_to questions_path, notice: "Question deleted"
    else
      redirect_to question_path, error: "We had a problem deleting your question"
    end
  end

  def new
    @question = Question.new
  end

  private 

  def question_attributes
    params.require(:question).permit([:title,:description, {category_ids: []}]) 
  end

  def find_question
    @question = current_user.questions.find(params[:id])
  end


end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/help/index.html.haml
= link_to "About_us", root_url
= link_to "Edit Question", edit_question_path(1)
%h1 Index

app/views/home/about.html.haml
%h1 THIS COMES AFTER

app/views/home/index.html.haml
%h1 Test Page

%p
  Task:
  =text_field_tag 'task', nil, class: 'add-task'
  %span#reverse
//%ul#task-list 


/ .well
/   Here is one
/   .btn.btn-danger.pull-right.remove
/     Remove
/ .well
/   Here is two
/   .btn.btn-danger.pull-right.remove
/     Remove
/ .well
/   Here is three
/   .btn.btn-danger.pull-right.remove
/     Remove
/ .well
/   Here is four
/   .btn.btn-danger.pull-right.remove
/     Remove
/ .well
/   Here is five
/   .btn.btn-danger.pull-right.remove
/     Remove

app/views/home/password.html.haml
%h1 Password Strength
.row
  .col-lg-6
    =password_field_tag :password, nil, class: "form-control", id: "password"
  #passMessage.col-lg-6.bg-warning
    whatever

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title AwesomeAnswers
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .navbar-brand= link_to "AWESOME ANSWERS", questions_path
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to "Add a new Question", new_question_path
          .pull-right
            - if user_signed_in?
              = link_to "Sign Out", destroy_user_session_path, method: :delete
            - else
              = link_to "Sign In", new_user_session_path 

    .container
      - if flash[:notice]
        .alert.alert-success
          = flash[:notice]
      - elsif flash[:error]
        .alert.alert-danger
          = flash[:error]  
      = yield

app/views/questions/_answer.html.haml
- if @answer.errors.any?
  %h3.field_with_errors ERRRORSSSSS!!!!!!
  .alert.alert-danger
    %ul
      - @answer.errors.full_messages.each do |m|
        %li= m

/ = form_for [@question, @answer] do |f|
= form_for @answer, url: question_answers_path(@question) do |f|
  = f.text_area :body
  = f.submit "Submit an answer"

app/views/questions/_form.html.haml
- if @question.errors.any?
  %h3.field_with_errors ERRRORSSSSS!!!!!!
  .alert.alert-danger
    %ul
      - @question.errors.full_messages.each do |m|
        %li= m
= form_for @question do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :description
    = f.text_area :description, class: "form-control"
  .form-group
    = f.collection_check_boxes :category_ids, Category.order("title"), :id, :title
  .form-group
    = f.submit class: "btn btn-primary"
.container
  - if flash[:notice] || flash[:error]
    .alert.alert-success
      = flash[:notice]
  = yield

app/views/questions/destroy.html.erb
delete <%= @id %>

app/views/questions/edit.html.haml
%h1 Edit
= render "form"

app/views/questions/index.html.haml
%h1 List all of the questions
- @questions.each do |question|
  %h2= link_to question.title, question
  %p= question.description
  %p
    Created On: #{question.created_at.strftime("%Y-%b-%d")}
  %hr/

app/views/questions/new.html.haml
%h1 Add a new Question
- if @question.errors.any?
  %h3.field_with_errors ERRRORSSSSS!!!!!!
  .alert.alert-danger
    %ul
      - @question.errors.full_messages.each do |m|
        %li= m
= render "form"

app/views/questions/show.html.haml
%h1= @question.title
%p
  - if @question.categories.present?
    Categories (#{@question.categories.count}):
    = @question.categories.map(&:title).join(", ")
%p
  Vote count: #{@question.vote_count}
%p= button_to "Vote Up", vote_up_question_path(@question)
%p= @question.description
%p
  Created on: #{@question.created_at.strftime("%F")}
%p
  = link_to "Edit Question", edit_question_path(@question), class: "btn btn-warning"
  = link_to "Delete", @question, method: :delete, data: {confirm: "Are you sure you want to delete this question?"}, class: "btn btn-danger"
%h2 Answer Question
= render "answer"

%h2 Answers
- @question.answers.each do |answer|
  .well
    %p= answer.body
    %p
      Created On: #{answer.created_at.strftime("%Y-%b-%d")}